### ISSUE TITLE
자동 로그인 로직, 파이어베이스 설계

### ISSUE THREAD

**Issue by ungchun** [ungchun/DailyRecord#13]
## 🛠 Issue
Domain, Data layer에 맞춰 파이어베이스 설계를 재구성합니다.

## 📝 To-do

- [x] 싱글턴 구조 설계
- [x] 자동 로그인 로직
- [x] 네트워크 layer 설계
