### ISSUE TITLE
1.0.0 배포 전 로직 체크 및 코드 정리

### ISSUE THREAD

**Issue by ungchun** [ungchun/DailyRecord#24]
## 🛠 Issue
1.0.0 배포 준비를 하면서 테스트를 합니다.

## 📝 To-do

- [x] UserDefault 데이터 KeyChain으로 변경
- [x] 익명 -> 애플로그인으로 데이터 이전하는 방법 + 익명, 애플 로그인 로직 테스트
- [x] 코드 정리
- [x] 앱 이름, 아이콘 변경
