### ISSUE TITLE
배포 전 마지막 남은 기능

### ISSUE THREAD

**Issue by ungchun** [ungchun/DailyRecord#26]
## 🛠 Issue
배포 전 마지막 남은 기능을 추가합니다.

## 📝 To-do

- [x] 처음 작성하면 입장할 때 감정표현 alert 바로 뜨는 로직 추가
- [x] 이미지 클릭 시 이미지 전체 화면으로 좌우로 스크롤 되는 뷰 추가
- [x] 다크모드, 라이트모드, 시스템 설정
